### PR TITLE
add quotation mark for String

### PR DESCRIPTION
**Pull request by Rory-Z**
if the string element have forbidden characters or the string is a empty string, then add quotation mark for them
More info, please check https://go.dev/play/p/6blMUYTercu

### CODE REVIEW

**Comment by gurkankaymak** [comment]
Hi @Rory-Z, sorry for the late response, 
The regex appears to me not very readable can you update it to be more explicit, since there are only a handful of forbidden characters,
For instance, using the regex [$"{}[\]:=,`^?!@*&\\()] would make it clearer

**Comment by Rory-Z** [comment]
> Hi @Rory-Z, sorry for the late response, The regex appears to me not very readable can you update it to be more explicit, since there are only a handful of forbidden characters, For instance, using the regex [$"{}[]:=,`^?!@*&\()] would make it clearer

Good idea, let me try it.

**Comment by Rory-Z** [comment]
Hi @gurkankaymak Please review again

**Review by gurkankaymak — APPROVED** [review]

**Comment by Rory-Z** [comment]
Thanks for your approved, can we merge this ?

**Comment by sobotklp** [comment]
Are you sure this is the expected behavior for parsing quoted strings containing forbidden chars? For example, if my HOCON file looks like this:
```
endpoint = "127.0.0.1:6379" // Contains forbidden chars periods and colon
```

Then loading that via `conf.GetString("endpoint")` would have quotes in the resulting string. i.e.
```
endpoint := conf.GetString("endpoint")
fmt.Println(endpoint) // output includes the quotes i.e. "127.0.0.1:6379"
```
but I would have expected the quotes to be stripped.

**Comment by acheong08** [comment]
This definitely feels like the wrong behavior. Why would we want to quote the string?

**Pull request merged**
