### PR TITLE
fix: fix the object String() function error when the element have ":"

### PR DESCRIPTION
**Pull request by Rory-Z**
Fix https://github.com/gurkankaymak/hocon/issues/16

### CODE REVIEW

**Comment by gurkankaymak** [comment]
thanks for the contribution, requested minor test changes otherwise looks good to me

**Comment by Rory-Z** [comment]
> thanks for the contribution, requested minor test changes otherwise looks good to me

What do I need to do ?

**Comment by gurkankaymak** [comment]
you can see line comments above, I think tests should be added as a separate case, in example

> t.Run("return the string of an object that contains a string element with the ':' character", func(t *testing.T) {
		got := Object{"a": String("0.0.0.0:80")}.String()
		assertEquals(t, got, `{a:"0.0.0.0:80"}`)
	})

**Comment by Rory-Z** [comment]
> you can see line comments above, I think tests should be added as a separate case, in example
> 
> > t.Run("return the string of an object that contains a string element with the ':' character", func(t *testing.T) {
> > got := Object{"a": String("0.0.0.0:80")}.String()
> > assertEquals(t, got, `{a:"0.0.0.0:80"}`)
> > })

Cool, I will change code

**Comment by Rory-Z** [comment]
When do we plan to release the next version? I'm looking forward to it.

**Comment by gurkankaymak** [comment]
just published a new release https://github.com/gurkankaymak/hocon/releases/tag/v1.2.7

**Comment by Rory-Z** [comment]
> just published a new release https://github.com/gurkankaymak/hocon/releases/tag/v1.2.7

So cooooooool

**Pull request merged**
